export const colors = {
  fondo: "#FAFAF5",
  letraTitulos: "#4DBDEB",
  fondoSecundario: "#DFEEEE",
  botonFondo: "#FFE08C",
  letraSecundaria: "#434141",
  cargando: "#007AFF",
  infoLetra: "#555",
  error: "#FF4D4F",
  ofertaMonetaria: "#D0E8FF",
  ofertaIntercambio: "#FFF4D0",
  exito: "#28C76F",
    estadoPendiente: "#FFA500", 
  estadoAceptado: "#32CD32",  
  estadoPagoPendiente: "#FF8C00", 
  estadoPagado: "#006400",   
  estadoCompletado: "#1E90FF",
  estadoRechazado: "#FF0000", 
  estadoCancelado: "#A9A9A9"
};
